### ISSUE TITLE
Pseudo Attributes

### ISSUE THREAD

**Issue by brather1ng** [brather1ng/PoESkillTree#5]
So I thought a bit about how to define the pseudo attributes and I think hardcoding them isn't the best. I would say some kind of XML data structure would be good.
Something like this (for increased phys dmg, should be complete and pretty self-explanatory):
```XML
<PseudoAttribute Name="#% increased Physical Damage">
    <Attribute Name="#% increased Physical Damage"/>
    <Attribute Name="#% increased Physical Damage with $1">
        <Conditions>
            <AndComposition>
                <WeaponClass>$1</WeaponClass> <!-- Maces, Axes, Two Handed Melee Weapons, ... -->
                <Tag>Attack</Tag>
            </AndComposition>
            <Tag>$1</Tag><!-- Attacks -->
        </Conditions>
    </Attribute>
    <Attribute Name="#% increased Melee Physical Damage">
        <Conditions>
            <Tag>Melee</Tag>
        </Conditions>
    </Attribute>
    <Attribute Name="#% increased Physical Damage while holding a Shield">
        <Conditions>
            <OffHand>Shield</OffHand>
        </Conditions>
    </Attribute>
    <Attribute Name="#% increased Physical Damage while Dual wielding or holding a Shield">
        <Conditions>
            <OffHand>DualWield</OffHand>
            <OffHand>Shield</OffHand>
        </Conditions>
    </Attribute>
    <Attribute Name="+# to Strength" ConversionRate=".2">
        <Conditions>
            <Tag>Melee</Tag>
            <AndComposition>
                <WeaponClass>Bow</WeaponClass>
                <Keystone>Iron Grip</Keystone>
            </AndComposition>
        </Conditions>
    </Attribute>
    <Attribute Name="#% increased Physical Damage over Time">
        <Conditions>
            <Tag>DoT</Tag>
        </Conditions>
    </Attribute>
</PseudoAttribute>
```
Best case would be if the format could be made deserializable so no parse code is needed at all.

**Comment by MLanghof** [comment]
Wait, are the conditions or'd or and'd?

**Comment by brather1ng** [comment]
If not in an `<AndComposition>`, they are or'd.

**Comment by MLanghof** [comment]
So would you expect users to customize this in the xml format?
I don't understand at the moment how exactly this would be used in the tool. Would the user specify the skill in use? Would it support support gems (totems/traps/mines)?

**Comment by brather1ng** [comment]
No no, this would basically be the definition of the pseudo attributes and how they are calculated (which would otherwise need to be hardcoded into the code).
The user wouldn't see those files at all, only the names of the pseudo attributes he can choose.

Support gems or gems at all are not what I planned to include in pseudo attribute calculation, though that would be possible.
But the program still needs to know some things about the build to decide which attributes are included in pseudo attributes, so the user could choose weapon type, dual wield/shield/two handed and if the calculations are for melee/projectile/spell/ranged attack/AoE/... (for all attributes, could be theoratically extended to be done on groups of attributes)
So a fireball staff guy that is only interested in the initial damage increase would choose staff, two handed, projectile and spell and than put in "#% increased Fire Damage" as a pseudo attribute for example.

I most likely forgot some stuff but this is what I have planned for the inital step of pseuod attributes.
